/** BOOKS ACTIONS */
export const REQUEST_BOOKS = "REQUEST_BOOKS";
export const RECEIVE_BOOKS = "RECEIVE_BOOKS";
export const FAILED_BOOKS = "FAILED_BOOKS";
export const SET_BOOK_QUERY = "SET_BOOK_QUERY";

/** BOOKSHELF ACTIONS */
export const REQUEST_BOOKSHELF = "REQUEST_BOOKSHELF";
export const RECEIVE_BOOKSHELF = "RECEIVE_BOOKSHELF";
export const FAILED_BOOKSHELF = "FAILED_BOOKSHELF";
export const CHANGE_BOOKSHELF = "CHANGE_BOOKSHELF";
